### ISSUE TITLE
Wifi logo missing on sidebar 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/wifi#23]
Testing sidebar PR https://github.com/emoncms/wifi/pull/22 the WiFi logo is missing

![Screenshot 2019-04-27 at 15 30 56](https://user-images.githubusercontent.com/758844/56850979-92c86080-6901-11e9-81b3-391834f61991.png)

**Comment by glynhudson** [comment]
Sorry, my bad. It was a cache issue :-(

**Comment by emrysr** [comment]
No the issue was that the svg icons are now inline withinin the emoncms `emoncms/Theme/basic/theme.php` file. Once you pulled the recent changes within https://github.com/emoncms/emoncms you also downloaded the icon for this module.

@glynhudson this might be better done by including the icon in with the module..?
